### ISSUE TITLE
Use scratch image?

### ISSUE THREAD

**Issue by gutenye** [tianon/docker-syncthing#3]
Check out https://blog.docker.com/2016/09/docker-golang/#h.mjk4x1sqxv2z

**Comment by tianon** [comment]
I like the idea, but the main problem is that it would require me to check the upstream `syncthing` binaries into this Git repo in order to be really effective, and I think that approach loses some of the provenance of the raw upstream binaries I'm including (especially making it much more difficult to take an image that's been pushed and verify that the binaries contained within it are the same as the binaries upstream publishes, which having Alpine's minimal shell and package manager helps facilitate).
